name: 🚀 Deploy Web to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Execute Deployment SSH Command
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            cd /var/www/html/proyects/
            if [ -d "testDeploy/.git" ]; then
              echo "El repositorio ya existe, haciendo pull..."
              cd testDeploy
              git pull
            else
              if [ -d "testDeploy" ]; then
                echo "Existe testDeploy pero NO es repo, borrando carpeta..."
                rm -rf testDeploy
              fi
              echo "Clonando repo..."
              git clone ${{ secrets.VPS_REPO_URL }}
            fi


